version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: glimpse-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: glimpse_db
      MYSQL_USER: glimpse_user
      MYSQL_PASSWORD: glimpse_password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - glimpse-mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: glimpse-backend
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/glimpse_db
      - SPRING_DATASOURCE_USERNAME=glimpse_user
      - SPRING_DATASOURCE_PASSWORD=glimpse_password
      - APP_ADMIN_USERNAME=admin
      - APP_ADMIN_PASSWORD=change_me

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: glimpse-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  glimpse-mysql-data:
